[pytest]
<<<<<<< HEAD
addopts = --cov=app --cov-report=term-missing
testpaths = tests
=======
pythonpath = .
testpaths = tests

# Enable coverage reporting for both app/ and main.py
addopts = --cov=app --cov=main --cov-report=term-missing
>>>>>>> origin/version5
