"""
Parameterized tests for arithmetic operations using Faker for test data generation.
"""
import pytest
import math
from src.calculator import Calculator
from src.commands.arithmetic_commands import (
    AddCommand, SubtractCommand, MultiplyCommand, DivideCommand
)
from src.commands.power_command import PowerCommand


class TestArithmeticParameterized:
    """
    Parameterized tests for arithmetic operations with Faker-generated data.
    This test class uses pytest's parameterization to run the same tests
    with multiple sets of random test data.
    """
    
    def test_arithmetic_operations(self, num1, num2, operation, expected_result):
        """
        Test arithmetic operations with parameterized data.
        
        This test will run multiple times with different random values
        generated by the fixtures defined in conftest.py.
        
        Args:
            num1: First number for the operation
            num2: Second number for the operation
            operation: Name of the operation to perform
            expected_result: Expected result of the operation
        """
        # Get the appropriate command based on the operation name
        if operation == "add":
            cmd = AddCommand()
            result = cmd.execute(num1, num2)
        elif operation == "subtract":
            cmd = SubtractCommand()
            result = cmd.execute(num1, num2)
        elif operation == "multiply":
            cmd = MultiplyCommand()
            result = cmd.execute(num1, num2)
        elif operation == "divide":
            cmd = DivideCommand()
            # Skip division by zero tests
            if abs(num2) < 0.0001:
                pytest.skip("Skipping division by zero")
            result = cmd.execute(num1, num2)
        elif operation == "power":
            cmd = PowerCommand()
            result = cmd.execute(num1, num2)
        else:
            pytest.skip(f"Skipping unsupported operation: {operation}")
        
        # Check if result is close to expected_result
        # We use math.isclose for floating point comparison
        if math.isnan(result) and math.isnan(expected_result):
            assert True  # Both are NaN
        elif math.isinf(result) and math.isinf(expected_result):
            assert True  # Both are Inf with same sign
        else:
            # For regular values, use isclose with appropriate tolerance
            assert math.isclose(result, expected_result, rel_tol=1e-9, abs_tol=1e-9), \
                f"{operation}({num1}, {num2}) = {result}, expected {expected_result}"
